# Configuration file of StarLoco

# Rate server
rate.xp=1.5
xp.degressive.enabled=true
xp.degressive.ranges=1-100:6.0,101-170:3.5,171-190:2.5,191-200:1.5
rate.job=5
rate.farm=3
rate.honor=1
rate.kamas=2
rate.fm=1
rate.percent-exo=2

# TCP Connection
server.host=127.0.0.1
server.port=5555
server.id=2
server.version=1.42.7
server.name=Aethyra
server.key=aethyra

exchange.host=127.0.0.1
exchange.port=666

# Database connection
database.login.host=127.0.0.1
database.login.port=3306
database.login.user=root
database.login.pass=Jaimelaweed33
database.login.name=login

database.game.host=127.0.0.1
database.game.port=3306
database.game.user=root
database.game.pass=Jaimelaweed33
database.game.name=game


# Activer ou dï¿½sactiver les options
# Si le serveur tourne sur Linux, mettre mode.linux=true
mode.linux=false
# Si le serveur doit enregistrer les logs (Logs de connexion, Erreurs, etc.)
mode.log=true
# Si le serveur doit nettoyer les donnï¿½es inutiles automatiquement (Logs, Anciens personnages, etc.)
mode.autoClean=false
# Si le serveur doit considï¿½rï¿½ tous les HDV comme global (Tous les HDV sont regroupï¿½s)
mode.hdvGlobal=true
# Si le serveur doit utiliser un bot Discord pour les commandes
mode.discordBot=false
# Si le serveur doit envoyer des notifications sur Discord via des webhooks
mode.discordWebhooks=false

# Prix en Point de Vote pour les services
prix.prix-changement-classe=400
prix.prix-changement-couleur=200
prix.prix-changement-pseudo=200

#Paramï¿½trages pour le mode autoClean
autoClean.characters=true
autoClean.guilds=true
# Chiffre en mois pour la durï¿½e de conservation des comptes
autoClean.maximumDate=9
autoClean.ignoreVIP=true

# Pour le bot discord (Si vous avez activï¿½ le mode.discordBot uniquement)
discord.key=
discord.channelId.command=

# Pour les webHook Discord (Si vous avez activï¿½ le mode.discordWebhooks uniquement)
discord.channelId.faille=https://discord.com/api/webhooks/1495082261421228193/T4HhHOP8DIKRbm1zotU3nbXCcy8jyAu8rFhinf0B5ollv8EQf2oMurbbREGHUEruRvOq
discord.channelId.event=
discord.channelId.info=https://discord.com/api/webhooks/1495082101857587241/BSICVgpsJFz8AJbpvlqE9RSuO-R6nKsIwHyqvWHQBbavzF_yQ8pUSPH-ljjc5aOrmJf1
discord.channelId.log=https://discord.com/api/webhooks/1495082179917516870/w0KmPb52eexaOExeBLTx07xoB7Lx2dQGKrC-kUY1TQLdgu9-xtw548iyPA4DAifgzLSQ

# Extra options
mode.halloween=false
mode.christmas=true
mode.heroic=false
options.start.message="Bienvenue sur Aethyra !"
options.start.map=0
options.start.cell=0
options.start.kamas=0
options.start.level=1
options.event.active=false
options.event.timePerEvent=2
options.autoReboot=true
options.encryptPacket=true
options.gladiatrool=true
options.teamMatch=true
options.deathMatch=false
options.allZaap=true
options.allEmote=true
options.subscription=false

# Roulette - Add by Kytz
ruleta.objetos=35050:13.5,10158:2.5,6716:6.5,35000:12.5,8952:22.5,8949:22.5,8955:13.5,35001:6.5
ruleta.ticket=35001

# ticket ID = 35001 ; idItem:1.5 = taux de chance sur 100 / 8

# End of configuration
